services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.7.3-python3.11
    entrypoint: /bin/bash
    command: -c "/opt/airflow/airflow-init.sh"
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      PYTHONPATH: /opt/airflow:/opt/airflow/tools
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./tools:/opt/airflow/tools
      - ./chroma:/chroma
      - ./airflow-init.sh:/opt/airflow/airflow-init.sh
      - ./db:/opt/airflow  # db.init marker will live here
    depends_on:
      - postgres

  streamlit:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./ui:/ui

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

volumes:
  postgres-db-volume:
  ollama-data: